apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-repository.yaml
  - cert-manager.yaml
  - namespace.yaml
  - repository.yaml
  - operator.yaml

  - collector.yaml
