apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus-repository.yaml
  - prometheus.yaml
  - grafana-repository.yaml
  - loki.yaml
  - fluent-repository.yaml
  - fluent-bit.yaml

  - grafana.yaml
